@echo off

echo Running git pulls of batch files...
call f:\batch_files\__common_git_pull.sh
echo Running git pulls of cpp files...
call f:\cpp_files\__common_git_pull.sh
echo Running git pulls of lua files...
call f:\lua_files\__common_git_pull.sh
echo Running git pulls of working note files...
call f:\working_notes_of_Miniworld\__common_git_pull.sh
echo Finish all git pulls.