@echo off

echo Running git pushes of batch files...
call f:\batch_files\__common_git_add_commit_push.sh
echo Running git pushes of cpp files...
call f:\cpp_files\__common_git_add_commit_push.sh
echo Running git pushes of lua files...
call f:\lua_files\__common_git_add_commit_push.sh
echo Running git pushes of working note files...
call f:\working_notes_of_Miniworld\__common_git_add_commit_push.sh
echo Finish all git pushes.